apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: nats-streaming:0.19.0-alpine
          ports:
            - containerPort: 8222
            - containerPort: 4222
          volumeMounts:
            - name: broker-data
              mountPath: /datastore
          command: ["nats-streaming-server"]
          args:
            [
              "-st",
              "FILE",
              "--dir",
              "/datastore",
              "-m",
              "8222",
              "-D",
              "-SD",
              "-cid",
              "broker-cluster",
            ]
      volumes:
        - name: broker-data
          persistentVolumeClaim:
            claimName: broker-data-claim
