kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-pv
  labels:
    app: broker
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/datastore"
