apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagesapi
  labels:
    app: messagesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagesapi
  template:
    metadata:
      labels:
        app: messagesapi
    spec:
      containers:
        - name: messagesapi
          image: leolanavo/messages-api:0.2.5
          ports:
            - containerPort: 3000
